import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import './components/styles/_default_form_config.scss';

export const metadata = {
  title: "Test Work ",
  description: "Generated by create Anyhr.io",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='body'>{children}</body>
    </html>
  );
}
