import Head from "next/head";
import '../components/styles/_section4_module_style.scss';
import '../components/styles/_default_form_config.scss';
import '../components/styles/_ssg_style.scss';
import CatalogBasisFilter from "../components/CatalogOwn";
import Footer from "../components/Footer";

export default function Home() {

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main>
          <div className="ssg__info">
            <h1>SSG</h1>
          </div>
          <CatalogBasisFilter/>
        </main>
      </>
    )
  }